/*
 * This file was autogenerated by TinyMPC on Wed Nov  8 10:09:38 2023
 */

#pragma once

#include "types.hpp"

#ifdef __cplusplus
extern "C" {
#endif

extern TinySolver tiny_data_solver;

#ifdef __cplusplus
}
#endif
