/*
 * This file was autogenerated by TinyMPC on Thu Nov  2 19:26:25 2023
 */

#pragma once

#include "types.hpp"

#ifdef __cplusplus
extern "C" {
#endif

extern TinySolver tiny_data_solver;

ifdef __cplusplus
}
#endif
