/*
 * This file was autogenerated by  on Sun Oct  8 17:41:27 2023
 *
 * This file contains the prototype for the solver structure needed
 * by . The actual data is contained inside osqp_data_workspace.c.
 */

#pragma once

#include "types.hpp"

#ifdef __cplusplus
extern "C"
{
#endif

    extern TinySolver tiny_data_solver;

#ifdef __cplusplus
}
#endif