/*
 * This file was autogenerated by TinyMPC on Sat Nov 11 22:48:28 2023
 */

#pragma once

#include "types.hpp"

#ifdef __cplusplus
extern "C" {
#endif

extern TinySolver tiny_data_solver;

#ifdef __cplusplus
}
#endif
