/*
 * This file was autogenerated by TinyMPC on Tue Oct 31 16:26:24 2023
 * 
 * This file contains a sample solver to run the embedded code.
 */

#include <tinympc/tiny_data_workspace.hpp>

#ifdef __cplusplus
extern "C" {
#endif

/* User settings */
TinySettings settings = {
	(tinytype)0.0010000000474975,	// primal tolerance
	(tinytype)0.0010000000474975,	// dual tolerance
	100,		// max iterations
	1,		// iterations per termination check
	1,		// enable state constraints
	1		// enable input constraints
};

/* Matrices that must be recomputed with changes in time step, rho */
TinyCache cache = {
	(tinytype)0.1000000014901161,	// rho (step size/penalty)
	(tiny_MatrixNuNx() << (tinytype)0.2207463532686234,(tinytype)0.1022121012210846,(tinytype)0.2699414491653442,(tinytype)1.1118340492248535).finished(),
	(tiny_MatrixNxNx() << (tinytype)1.2268637418746948,(tinytype)0.3853992819786072,(tinytype)0.3853999972343445,(tinytype)4.7949771881103516).finished(),
	(tiny_MatrixNuNu() << (tinytype)0.0284910034388304,(tinytype)-0.0506565682590008,(tinytype)-0.0506565645337105,(tinytype)0.1394513845443726).finished(),
	(tiny_MatrixNxNu() << (tinytype)0.0311245918273926,(tinytype)0.8546733856201172,(tinytype)0.0148024559020996,(tinytype)-0.1915998458862305).finished(),
	(tiny_MatrixNxNu() << (tinytype)0.0000044107437134,(tinytype)0.0000041723251343,(tinytype)0.0000010579824448,(tinytype)0.0000011920928955).finished(),
};

/* Problem variables */
TinyWorkspace work = {
	(tiny_MatrixNxNh() << (tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000).finished(),
	(tiny_MatrixNuNhm1() << (tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000).finished(),
	(tiny_MatrixNxNh() << (tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000).finished(),
	(tiny_MatrixNuNhm1() << (tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000).finished(),
	(tiny_MatrixNxNh() << (tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000).finished(),
	(tiny_MatrixNuNhm1() << (tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000).finished(),
	(tiny_MatrixNxNh() << (tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000).finished(),
	(tiny_MatrixNxNh() << (tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000).finished(),
	(tiny_MatrixNuNhm1() << (tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000).finished(),
	(tiny_MatrixNuNhm1() << (tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000).finished(),
	(tiny_MatrixNxNh() << (tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000).finished(),
	(tiny_MatrixNuNhm1() << (tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000).finished(),
	(tinytype)0.0000000000000000,	// state primal residual
	(tinytype)0.0000000000000000,	// input primal residual
	(tinytype)0.0000000000000000,	// state dual residual
	(tinytype)0.0000000000000000,	// input dual residual
	0,	// solve status
	0,	// solve iteration
	(tiny_VectorNx() << (tinytype)1.1000000238418579,(tinytype)1.1000000238418579).finished(),
	(tiny_VectorNx() << (tinytype)1.1000000238418579,(tinytype)1.1000000238418579).finished(),
	(tiny_VectorNu() << (tinytype)2.0999999046325684,(tinytype)2.0999999046325684).finished(),
	(tiny_MatrixNxNx() << (tinytype)1.0000000000000000,(tinytype)1.0000000000000000,(tinytype)5.0000000000000000,(tinytype)2.0000000000000000).finished(),
	(tiny_MatrixNxNu() << (tinytype)3.0000000000000000,(tinytype)4.0000000000000000,(tinytype)3.0000000000000000,(tinytype)1.0000000000000000).finished(),
	(tiny_MatrixNuNhm1() << (tinytype)-0.5000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000).finished(),
	(tiny_MatrixNuNhm1() << (tinytype)0.5000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000).finished(),
	(tiny_MatrixNxNh() << (tinytype)-1.1000000238418579,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000).finished(),
	(tiny_MatrixNxNh() << (tinytype)1.1000000238418579,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000).finished(),
	(tiny_MatrixNxNh() << (tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000).finished(),
	(tiny_MatrixNuNhm1() << (tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000,(tinytype)0.0000000000000000).finished(),
	(tiny_VectorNu() << (tinytype)0.0000000000000000,(tinytype)0.0000000000000000).finished()
};

TinySolver tiny_data_solver = {&settings, &cache, &work};

#ifdef __cplusplus
}
#endif

